name: 'Build Plugin'
description: 'Build GOG Galaxy integration on current OS'

inputs:
  src:
    description: 'Location of directory containing manifest.json and essential plugin files'
    required: true
    default: 'src'
  target:
    description: 'Relative path to expected build directory' 
    required: true
  requirements:
    description: 'Location of Python requirements file'
    required: true
    default: 'requirements/app.txt'
  third-party-target:
    description: 'Target directory where pip packages are dumped; relative to `target`'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: OS guard
      run: echo "Only Windows (x86) and MacOS are supported!; exit 1
      shell: bash
      if: ${{ runner.os != 'windows' && runner.os != 'macOS' }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7.3'  # bundled with GOG Galaxy
        architecture: ${{ startsWith(runner.os, 'windows') && 'x86' || 'x64' }}
    - run: pip install fog.buildtools
      shell: bash
    - name: Build plugin
      shell: python
      run: |
        from fog.buildtools import build
        build(
          src='${{ inputs.src }}',
          output='${{ inputs.target }}',
          third_party_output='${{ inputs.third-party-target }}',
          requirements='${{ inputs.requirements }}',
        ) 
